In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('C:\\Users\\pkmra_fk94jjw\\Downloads\\titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


Setting 'Pclass','SibSp','Parch','Fare' columns as data and ‘Survived’ column as label

In [4]:
X=df[['Pclass','SibSp','Parch','Fare']]
y=df.Survived

In [5]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   SibSp   891 non-null    int64  
 2   Parch   891 non-null    int64  
 3   Fare    891 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 28.0 KB


# Model Building

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Logistic Regression

In [55]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [56]:
print('Accuracy::\n',accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy::
 0.7597765363128491
Confusion Matrix:
 [[110  13]
 [ 30  26]]


In [57]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores: {}\n".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.62569832 0.66853933 0.66853933 0.69662921 0.75280899]

Average Cross Validation score :0.6824430355909861


KNN

In [58]:
knn_classifier= KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
knn_classifier.fit(X_train, y_train)
y_pred = knn_classifier.predict(X_test)

In [59]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy: 0.7318435754189944
Confusion Matrix:
 [[94 29]
 [19 37]]


In [60]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(knn_classifier,X,y,cv=kf)
print("Cross Validation Scores: {}\n".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.60893855 0.64044944 0.69662921 0.69662921 0.75842697]

Average Cross Validation score :0.6802146757893415


SVM

In [61]:
svc=SVC(kernel='linear', C=1) 
svc.fit(X_train,y_train) 
y_pred=svc.predict(X_test)

In [62]:
print('Accuracy:\n',accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy:
 0.7541899441340782
Confusion Matrix:
 [[110  13]
 [ 31  25]]


In [63]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(svc,X,y,cv=kf)
print("Cross Validation Scores: {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.61452514 0.65730337 0.66292135 0.7247191  0.74719101]
Average Cross Validation score :0.6813319942250958


Decision tree

In [64]:
dectree = DecisionTreeClassifier()
dectree.fit(X_train,y_train)
y_pred=dectree.predict(X_test)

In [65]:
print('Accuracy:\n',accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy:
 0.7094972067039106
Confusion Matrix:
 [[95 28]
 [24 32]]


In [66]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(dectree,X,y,cv=kf)
print("Cross Validation Scores: {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.67039106 0.63483146 0.69662921 0.70786517 0.73033708]
Average Cross Validation score :0.6880107965601658


Random forest

In [67]:
rf_clf = RandomForestClassifier(random_state=42, n_estimators=100)
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)

In [68]:
print('Accuracy:\n',accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy:
 0.7094972067039106
Confusion Matrix:
 [[94 29]
 [23 33]]


In [69]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(rf_clf,X,y,cv=kf)
print("Cross Validation Scores: {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.63687151 0.64044944 0.68539326 0.73595506 0.73033708]
Average Cross Validation score :0.6858012679681125


Grid search

In [70]:
parameters ={'C': [0.1, 1, 10, 100, 1000],
             'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
             'kernel': ['rbf']}

In [71]:
grid_search = GridSearchCV(
    estimator=SVC(),
    param_grid=parameters, 
    cv=5,
    scoring='accuracy',
    n_jobs=-1)

In [72]:
grid_result= grid_search.fit(X_train, y_train)

In [73]:
print('Best Params: ', grid_result.best_params_)
print('Best Score: ', grid_result.best_score_)

Best Params:  {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
Best Score:  0.692406185363932


In [74]:
grid_predictions = grid_search.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))

[[104  19]
 [ 25  31]]


In [76]:
model = SVC(C=10, gamma=0.1,kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [77]:
print('Accuracy:\n',accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy:
 0.7541899441340782
Confusion Matrix:
 [[104  19]
 [ 25  31]]


In [78]:
#K-Fold Cross Validation to generalise the model accuracy
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores: {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores: [0.63687151 0.64606742 0.71910112 0.71348315 0.79213483]
Average Cross Validation score :0.7015316050467642
